Expose VirtualFitOptions class (#262)
Because virtual_fit is the name of the file and the function, it is not
possible to manually import VirtualFitOptions from the module path; the
following traceback occurs (in SlicerOpenLIFU):

```
Traceback (most recent call last):
  File "project/lib/Slicer-5.8/qt-scripted-modules/OpenLIFUProtocolConfig.py", line 270, in setup
    self.virtual_fit_options_definition_widget = OpenLIFUAbstractClassDefinitionFormWidget(cls=openlifu_lz().virtual_fit.VirtualFitOptions(), parent=self.ui.virtualFitOptionsDefinitionWidgetPlaceholder.parentWidget())
AttributeError: 'function' object has no attribute 'VirtualFitOptions'
```