Resolve circular imports during tests (#203)
Running most tests yielded the following error:

```
___________________ ERROR collecting tests/test_database.py ____________________
ImportError while importing test module '/home/runner/work/OpenLIFU-python/OpenLIFU-python/tests/test_database.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_database.py:12: in <module>
    from openlifu import Point, Solution
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/__init__.py:22: in <module>
    from openlifu.db import Database
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/db/__init__.py:1: in <module>
    from .database import Database
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/db/database.py:13: in <module>
    from openlifu.login import User
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/login/__init__.py:1: in <module>
    from .user import User
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/login/user.py:7: in <module>
    from openlifu.util.json import PYFUSEncoder
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/util/json.py:9: in <module>
    from openlifu.plan.solution_analysis import SolutionAnalysisOptions
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/plan/__init__.py:1: in <module>
    from .protocol import Protocol
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/plan/protocol.py:15: in <module>
    from openlifu.db.session import Session
/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/db/session.py:10: in <module>
    from openlifu.util.json import PYFUSEncoder
E   ImportError: cannot import name 'PYFUSEncoder' from partially initialized module 'openlifu.util.json' (most likely due to a circular import) (/opt/hostedtoolcache/Python/3.9.21/x64/lib/python3.9/site-packages/openlifu/util/json.py)
```

which was solved by moving PYFUSEncoder import inside get_encoder() to
fix a circular import in session.py. This ensures no premature
resolution issues.